# Site settings
title: 
email: 
description: "CC-BY Creative Commons Attribution"
baseurl: "http://jaume.barcelo.cc"
url: "http://jaume.barcelo.cc"
twitter_username: jaumebarcelo
github_username:  jbarcelo

# Build settings
markdown: kramdown
permalink: pretty
