# Site settings
title: "Jaume Barcelo"
email: 
description: "CC-BY Creative Commons Attribution"
baseurl: ""
url: "http://blog.jaumebarcelo.com"
twitter_username: jaumebarcelo
github_username:  jbarcelo

# Build settings
markdown: kramdown
permalink: pretty
